# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:
    include:
    - main
    - terraform-azure-devops
  paths:
    exclude: 
    - README.md
    - LICENSE

pool:
  vmImage: ubuntu-latest

#You can use this one if you have created the KeyVault and Cognitive Services manually.
variables:
  - group: "BagOfWords var group"

stages:
# You can use this one if you have created the KeyVault and Cognitive Services manually.
  # - stage: dev
  #   condition: succeededOrFailed()
  #   jobs:
  #   - template: /azure/templates/deploy.yml
  #     parameters:
  #       stageDeployment: dev
  #       awsSecret: $(aws-secret)
  #       awsKey: $(aws-key)  
  #       microsoftLocation: $(MICROSOFT-TRANSLATOR-LOCATION)
  #       microsoftSubscription: $(MICROSOFT-TRANSLATOR-SUBSCRIPTION-KEY)
  #       performTests: false

  - stage: terraform
    jobs:
    - template: /azure/templates/terraform.yml
      parameters:
        awsSecret: $(aws-secret)
        awsKey: $(aws-key)
  
  - stage: dev
    condition: succeededOrFailed()
    
    jobs:
    - job: 'CustomKeyVault'
      steps:
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'AzureDevOps'
          KeyVaultName: "BagOfWords3-kv"
          SecretsFilter: '*'
          RunAsPreJob: true
    - template: /azure/templates/deploy-using-tf-kv.yml
      parameters:
        stageDeployment: dev
        performTests: false
        awsSecret: $(aws-secret)
        awsKey: $(aws-key)
        microsoftLocation: $(MICROSOFT-TRANSLATOR-LOCATION)
        microsoftSubscription: $(MICROSOFT-TRANSLATOR-SUBSCRIPTION-KEY)