# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude: 
    - README.md
    - LICENSE

pool:
  vmImage: ubuntu-latest

variables:
  - group: "BagOfWords var group"

stages:      
  - stage: dev
    jobs:
    - template: /azure/deploy.yml
      parameters:
        stageDeployment: dev
        awsSecret: $(aws-secret)
        awsKey: $(aws-key)  
        microsoftLocation: $(MICROSOFT-TRANSLATOR-LOCATION)
        microsoftSubscription: $(MICROSOFT-TRANSLATOR-SUBSCRIPTION-KEY)