# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    install -g serverless 
  displayName: 'npm install packages & serverless'
- task: CmdLine@2
  inputs:
    script: 'serverless config credentials -o --provider aws --key $(aws-key) --secret $(aws-secret)'

- task: CmdLine@2
  inputs:
    script: 'rename serverless-copy.yml serverless.yml'

- task: CmdLine@2
  inputs:
    script: 'serverless deploy --verbose --stage dev --MICROSOFT_TRANSLATOR_SUBSCRIPTION_KEY $(MICROSOFT-TRANSLATOR-SUBSCRIPTION-KEY) --MICROSOFT_TRANSLATOR_LOCATION $(MICROSOFT-TRANSLATOR-LOCATION)'