# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude: 
    - README.md
    - LICENSE

parameters:
  - name: appName
    default: "BagOfWords"
    type: string
  - name: appLocation
    default: "East US"
    type: string
  - name: stage
    default: "dev"
    type: string

pool:
  vmImage: ubuntu-latest

#You can use this one if you have created the KeyVault and Cognitive Services manually.
variables:
  - group: "BagOfWords var group"

stages:
# You can use this one if you have created the KeyVault and Cognitive Services manually.
  # - stage: dev
  #   condition: succeededOrFailed()
  #   jobs:
  #   - template: /azure/templates/deploy.yml
  #     parameters:
  #       stageDeployment: dev
  #       awsSecret: $(aws-secret)
  #       awsKey: $(aws-key)  
  #       microsoftLocation: $(MICROSOFT-TRANSLATOR-LOCATION)
  #       microsoftSubscription: $(MICROSOFT-TRANSLATOR-SUBSCRIPTION-KEY)
  #       performTests: false

  - stage: terraform
    jobs:
    - template: /azure/templates/terraform-s3.yml
      parameters:
        awsSecret: $(aws-secret)
        awsKey: $(aws-key)
        appName: ${{ parameters.appName }}-${{${{ parameters.stage }}}}
        appLocation: ${{ parameters.appLocation }}
        serviceConnectionName: 'AzureDevOps'
        stageDeployment: ${{ parameters.stage }}
        cloudService: 'Azure'
        storageAccountName: bagofwordssa
  
  - stage: dev
    condition: succeededOrFailed()
    jobs:
    - template: /azure/templates/deploy-using-tf-kv.yml
      parameters:
        stageDeployment: dev
        performTests: false
        customKeyVaultName: "${{ parameters.appName }}-kv" #app_name-kv
        appName: ${{ parameters.appName }}