# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: "BagOfWords var group"

stages:
  - stage: configure
    jobs:
      - job: RenameFile
        steps:
        - task: CmdLine@2 
          inputs:
            script: 'mv serverless-copy.yml serverless.yml'
          displayName: 'Rename serverless.yml file'
  - stage: dev
    jobs:
    - template: /azure/deploy.yml
      parameters:
        stage: dev
        awsSecret: $(aws-secret)
        awsKey: $(aws-key)  
        microsoftLocation: $(MICROSOFT-TRANSLATOR-LOCATION)
        microsoftSubscription: $(MICROSOFT-TRANSLATOR-SUBSCRIPTION-KEY)