parameters:
  - name: stageDeployment
  - name: awsSecret
  - name: awsKey
  - name: microsoftLocation
  - name: microsoftSubscription

jobs:
- job: 'npm install packages & serverless'
  pool: 
    vmImage: ubuntu-latest
  steps:
  - template: /azure/templates/include-npm-step.yml
- job: 'Serverless configure & deploy'
  pool: 
    vmImage: ubuntu-latest
  steps:
  - template: /azure/templates/serverless-deploy.yml
    parameters:
        stage: dev
        awsSecret: ${{ parameters.awsSecret }}
        awsKey: ${{ parameters.awsKey }}
        microsoftLocation: ${{ parameters.microsoftLocation }}
        microsoftSubscription: ${{ parameters.microsoftSubscription }}