parameters:
  - name: stageDeployment
  - name: awsSecret
  - name: awsKey
  - name: microsoftLocation
  - name: microsoftSubscription
  - name: performTests

jobs:
- job: 'Tests'
  condition: eq(${{ parameters.stageDeployment }}, 'true')
  pool: 
    vmImage: ubuntu-latest
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
      npm install -D
    displayName: 'npm install & devDependencies'
  - script: |
      npm run test -- --watchAll=false
    displayName: 'perform tests'
    
- job: 'ConfigApp_${{ parameters.stageDeployment }}'
  pool: 
    vmImage: ubuntu-latest
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'
    
  - task: CmdLine@2 
    inputs:
      script: 'mv serverless-copy.yml serverless.yml'
    displayName: 'Rename serverless.yml file'

  - script: |
      npm install
      npm install -g serverless
    displayName: 'npm install packages & serverless'

  - task: CmdLine@2
    inputs:
      script: 'serverless config credentials -o --provider aws --key ${{ parameters.awsKey }} --secret ${{ parameters.awsSecret }}'
    displayName: "Configure serverless with AWS credentials"

  - task: CmdLine@2
    inputs:
      script: 'serverless deploy --verbose --stage ${{ parameters.stageDeployment }} --MICROSOFT_TRANSLATOR_SUBSCRIPTION_KEY ${{ parameters.microsoftSubscription }} --MICROSOFT_TRANSLATOR_LOCATION ${{ parameters.microsoftLocation }}'
    displayName: "Deploy ${{ parameters.stageDeployment }}"