jobs:
- job: 'Tests'
  pool: 
    vmImage: ubuntu-latest
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
      npm install -D
    displayName: 'npm install & devDependencies'
  - script: |
      npm run test --watchAll=false
    displayName: 'perform tests'