parameters:
  - name: awsSecret
  - name: awsKey

jobs:
- job: 'Environment'
  pool: 
    vmImage: ubuntu-latest
  steps:
  # - script: |
  #     az login --service-principal --username $(CLIENT-ID) --password $(CLIENT-SECRET) --tenant $(TENANT-ID)
  #   displayName: 'AZ Login'  
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    inputs:
      terraformVersion: 0.14.7
    displayName: 'Install Terraform'
  - task: TerraformCLI@0
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-main'
      allowTelemetryCollection: true
      displayName: 'Terraform init'
  - task: TerraformCLI@0
    inputs:
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-main'
      allowTelemetryCollection: true
      commandOptions: -input=false -var "app_name=BagOfWords2" -var "subscription_id=$(SUBSCRIPTION-ID)" -var "client_id=$(CLIENT-ID)" -var "client_secret=$(CLIENT-SECRET)" -var "tenant_id=$(TENANT-ID)" -var "location=East US" -var "aws_secret=$(awsSecret)" -var "aws_key=$(awsKey)"
      displayName: 'Terraform plan'
      runAzLogin: true
      environmentServiceName: 'AzureDevOps'
