# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude: 
    - README.md
    - LICENSE
    include:
    - src
    - terraform-main

parameters:
  - name: appName
    default: "BagOfWords"
    type: string
  - name: appLocation
    default: "East US"
    type: string
  - name: stage
    default: "dev"
    type: string

pool:
  vmImage: ubuntu-latest

#You can use this one if you have created the KeyVault and Cognitive Services manually.
variables:
  - group: "BagOfWords var group"

stages:
  - stage: dev
    jobs:
      # - job: 'Tests'
      #   steps:
      #     - template: /azure/templates/steps/node-tests.yml

      - job: 'ServerlessDeploy'
        steps:
          - template: /azure/templates/steps/serverless-node.yml
            parameters:
              stageDeployment: ${{parameters.stage}}
              performTests: false
              customKeyVaultName: "${{ parameters.appName }}-${{ parameters.stage }}-kv" #app_name-kv
              appName: ${{ parameters.appName }}
