name: Node.js CI

on:
  push:
    branches: "*"
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: backend
    # env:
    #   MONGO_USER: editor
    #   MONGO_PWD: passord
    #   MONGO_DB: db-connector

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm install
      
    - name: Install DEV dependencies
      run: npm install -D
      
    - name: Remove File Dictionary.test
      uses: JesseTG/rm@v1.0.2
      with:
        path: /__tests__/unit/Dictionary.test.js

    # - name: docker compose
    #   run: docker-compose up -d
      # uses: docker/build-push-action@v2
      # with:
      #   context: ./
      #   file: ./Dockerfile

    - name: perform tests with docker
      run: npm run gittest
        